# A simple testing example
# Tests fail if something is thrown
function foo() {
	print("Foo");
}

foo();

test "Doing Things" {
	foo();

	builtin.rand_seed_init();

	if builtin.rand_range(0, 10) <= 5 {
		throw "Random Bug";
	}
}

test "Doing Things More!!" {
	foo();

	builtin.rand_seed_init();

	while var idx = 0; idx < 10; idx = idx + 1 {
		if builtin.rand_range(0, 100) <= 10 {
			throw "Random Bug Again";
		}
	}
}